# -*- coding: utf-8 -*-
"""oop_workshop_pl (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bHzj6Aotr-vY8eFjaxTKapM4O6XCUwNu

# Warsztat Python OOP - Programowanie Obiektowe

Witaj na kompleksowym warsztacie z Programowania Obiektowego w Pythonie!

## 📋 Struktura Warsztatu

Ten notebook obejmuje:
1. Klasy i Obiekty - Podstawy
2. Hermetyzacja
3. Dziedziczenie
4. Polimorfizm
5. Abstrakcja
6. Metody Specjalne (Metody Magiczne)
7. Kompozycja
8. Metody Klasowe i Metody Statyczne
9. Wzorce Projektowe
10. Projekt Praktyczny

---
# Część 1: Klasy i Obiekty - Podstawy

## Czym są Klasy i Obiekty?

- **Klasa**: Szablon do tworzenia obiektów (jak foremka do ciastek)
- **Obiekt**: Instancja klasy (jak prawdziwe ciastko)
- **Atrybuty**: Dane przechowywane w obiekcie
- **Metody**: Funkcje należące do obiektu

## Podstawowa Składnia

```python
class ClassName:
    def __init__(self, param1, param2):
        self.attribute1 = param1
        self.attribute2 = param2
    
    def method_name(self):
        return self.attribute1
```

## Ćwiczenie 1.1: Utwórz Swoją Pierwszą Klasę

Utwórz klasę o nazwie `Book` z:
- Atrybuty: `title`, `author`, `pages`
- Metoda `display_info()` która wyświetla szczegóły książki
"""

# Twój kod tutaj:
class Book:
    def __init__(self, title, author, pages):
        self.title = title
        self.author = author
        self.pages = pages

    def display_info(self):
        print(f"'{self.title}' by {self.author}, {self.pages} pages")

# Przetestuj swój kod:
book1 = Book("1984", "George Orwell", 328)
book1.display_info()

book2 = Book("The Hobbit", "J.R.R. Tolkien", 310)
book2.display_info()

"""## Ćwiczenie 1.2: Praca z Wieloma Obiektami

Utwórz klasę `Student` z:
- Atrybuty: `name`, `student_id`, `grades` (list)
- Method `add_grade(grade)` dodającą ocenę do listy
- Method `calculate_average()` zwracającą średnią ocen
"""

# Twój kod tutaj:
class Student:
    def __init__(self, name, student_id):
        self.name = name
        self.student_id = student_id
        self.grades = []

    def add_grade(self, grade):
        if isinstance(grade, int) and 1 <= grade <= 6:
            self.grades.append(grade)
        else:
            print("Grade must be an integer from 1 to 6!")

    def calculate_average(self):
        if len(self.grades) == 0:
            return 0
        return sum(self.grades) / len(self.grades)


student1 = Student("Alice", "S001")

student1.add_grade(5)
student1.add_grade(6)
student1.add_grade(4)

print(f"{student1.name}'s average: {student1.calculate_average():.2f}")

# Przetestuj swój kod:
student1 = Student("Alice", "S001")
student1.add_grade(85)
student1.add_grade(90)
student1.add_grade(88)
print(f"{student1.name}'s average: {student1.calculate_average():.2f}")

"""## Ćwiczenie 1.3: Atrybuty Klasowe

Utwórz klasę `BankAccount` z:
- Atrybut klasowy: `bank_name = "Python Bank"`
- Atrybuty instancji: `account_number`, `owner`, `balance`
- Metody: `deposit(amount)`, `withdraw(amount)`, `get_balance()`
"""

# Twój kod tutaj:
class BankAccount:
    bank_name = "Python Bank"

    def __init__(self, account_number, owner, balance=0):
        self.account_number = account_number
        self.owner = owner
        self.balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"Deposited ${amount}. New balance: ${self.balance}")
        else:
            print("Deposit amount must be positive")

    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient funds")
        elif amount > 0:
            self.balance -= amount
            print(f"Withdrew ${amount}. New balance: ${self.balance}")
        else:
            print("Withdrawal amount must be positive")

    def get_balance(self):
        return self.balance

# Przetestuj swój kod:
account = BankAccount("ACC001", "John Doe", 1000)
print(f"Bank: {BankAccount.bank_name}")
account.deposit(500)
account.withdraw(200)
print(f"Final balance: ${account.get_balance()}")

"""### 💡 Rozwiązanie do Części 1"""

# Rozwiązanie 1.2: Student class
class StudentSolution:
    def __init__(self, name, student_id):
        self.name = name
        self.student_id = student_id
        self.grades = []

    def add_grade(self, grade):
        if 0 <= grade <= 100:
            self.grades.append(grade)
        else:
            print("Grade must be between 0 and 100")

    def calculate_average(self):
        if not self.grades:
            return 0
        return sum(self.grades) / len(self.grades)

# Rozwiązanie 1.3: BankAccount class
class BankAccountSolution:
    bank_name = "Python Bank"

    def __init__(self, account_number, owner, balance=0):
        self.account_number = account_number
        self.owner = owner
        self.balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"Deposited ${amount}. New balance: ${self.balance}")
        else:
            print("Deposit amount must be positive")

    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient funds")
        elif amount > 0:
            self.balance -= amount
            print(f"Withdrew ${amount}. New balance: ${self.balance}")
        else:
            print("Withdrawal amount must be positive")

    def get_balance(self):
        return self.balance

"""---
# Część 2: Hermetyzacja

## What is Hermetyzacja?

Hermetyzacja is the bundling of data and methods, while controlling access to that data.

## Access Modifiers in Python

- **Public**: `attribute` - Accessible from anywhere
- **Protected**: `_attribute` - Intended for internal use (convention)
- **Private**: `__attribute` - Name mangling (harder to access from outside)

## Why Hermetyzacja?

- Protect data integrity
- Control how data is accessed/modified
- Hide implementation details

## Ćwiczenie 2.1: Private Attributes

Utwórz klasę `Employee` z:
- Private attributes: `__name`, `__salary`
- Public methods: `get_name()`, `set_salary(amount)`, `get_salary()`
- Validation: salary must be positive
"""

# Twój kod tutaj:
class Employee:
    def __init__(self, name, salary):
        self.__name = name
        self.__salary = salary

    def get_name(self):
        return self.__name

    def set_salary(self, amount):
        if amount <= 0:
            raise ValueError("Salary must be positive")
        self.__salary = amount

    def get_salary(self):
        return self.__salary

# Przetestuj swój kod:
emp = Employee("Alice", 50000)
print(f"Name: {emp.get_name()}")
print(f"Salary: ${emp.get_salary()}")

emp.set_salary(55000)
print(f"New salary: ${emp.get_salary()}")

emp.set_salary(-1000)

"""## Ćwiczenie 2.2: Dekorator Propertys

Utwórz klasę `Temperature` z:
- Private attribute: `__celsius`
- Property `celsius` with getter and setter
- Property `fahrenheit` (calculated from celsius, read-only)
- Validation: celsius must be >= -273.15 (absolute zero)
"""

# Twój kod tutaj:
class Temperature:
    def __init__(self, celsius):
        self.celsius = celsius   # używa settera

    @property
    def celsius(self):
        return self.__celsius

    @celsius.setter
    def celsius(self, value):
        if value < -273.15:
            raise ValueError("Temperature cannot be below absolute zero")
        self.__celsius = value

    @property
    def fahrenheit(self):
        return (self.__celsius * 9/5) + 32

# Przetestuj swój kod:
temp = Temperature(25)
print(f"Celsius: {temp.celsius}°C")
print(f"Fahrenheit: {temp.fahrenheit}°F")

temp.celsius = 30
print(f"New Celsius: {temp.celsius}°C")
print(f"New Fahrenheit: {temp.fahrenheit}°F")

# Try setting invalid temperature
try:
    temp.celsius = -300
except ValueError as e:
    print(f"Error: {e}")

"""### 💡 Rozwiązanie do Części 2"""

# Rozwiązanie 2.1: Employee class
class EmployeeSolution:
    def __init__(self, name, salary):
        self.__name = name
        self.__salary = salary if salary > 0 else 0

    def get_name(self):
        return self.__name

    def set_salary(self, amount):
        if amount > 0:
            self.__salary = amount
        else:
            print("Salary must be positive")

    def get_salary(self):
        return self.__salary

# Rozwiązanie 2.2: Temperature class
class TemperatureSolution:
    def __init__(self, celsius):
        self.__celsius = celsius

    @property
    def celsius(self):
        return self.__celsius

    @celsius.setter
    def celsius(self, value):
        if value >= -273.15:
            self.__celsius = value
        else:
            raise ValueError("Temperature cannot be below absolute zero (-273.15°C)")

    @property
    def fahrenheit(self):
        return (self.__celsius * 9/5) + 32

"""---
# Część 3: Dziedziczenie

## What is Dziedziczenie?

Dziedziczenie allows a class to inherit attributes and methods from another class.

- **Base/Parent/Superclass**: The class being inherited from
- **Derived/Child/Subclass**: The class that inherits

## Why Use Dziedziczenie?

- Code reuse
- Hierarchical classification
- Polimorfizm support

## Syntax

```python
class Parent:
    pass

class Child(Parent):
    pass
```

## Ćwiczenie 3.1: Basic Dziedziczenie

Create a base class `Vehicle` z:
- Atrybuty: `brand`, `model`, `year`
- Method `start_engine()` that prints "Engine starting..."

Create a child class `Car` that:
- Inherits from `Vehicle`
- Adds attribute: `num_doors`
- Overrides `start_engine()` with a specific message
"""

# Twój kod tutaj:
class Vehicle:
    def __init__(self, brand, model, year):
        self.brand = brand
        self.model = model
        self.year = year

    def start_engine(self):
        print("Engine starting...")


class Car(Vehicle):
    def __init__(self, brand, model, year, num_doors):
        super().__init__(brand, model, year)  # dziedziczenie
        self.num_doors = num_doors

    def start_engine(self):
        print("Car engine starting... Vroom!")

# Przetestuj swój kod:
vehicle = Vehicle("Generic", "Vehicle", 2020)
vehicle.start_engine()

car = Car("Toyota", "Camry", 2023, 4)
car.start_engine()
print(f"This car has {car.num_doors} doors")

"""## Ćwiczenie 3.2: Multi-level Dziedziczenie

Create an inheritance chain:
1. `Animal` (base) - attributes: `name`, `species`
2. `Mammal` (inherits Animal) - adds: `fur_color`
3. `Dog` (inherits Mammal) - adds: `breed`, method `bark()`
"""

# Twój kod tutaj:
class Animal:
    def __init__(self, name, species):
        self.name = name
        self.species = species


class Mammal(Animal):
    def __init__(self, name, species, fur_color):
        super().__init__(name, species)
        self.fur_color = fur_color


class Dog(Mammal):
    def __init__(self, name, species, fur_color, breed):
        super().__init__(name, species, fur_color)
        self.breed = breed

    def bark(self):
        print("Woof! Woof!")

# Przetestuj swój kod:
dog = Dog("Buddy", "Canis familiaris", "Golden", "Golden Retriever")
print(f"Name: {dog.name}")
print(f"Species: {dog.species}")
print(f"Fur: {dog.fur_color}")
print(f"Breed: {dog.breed}")
dog.bark()

"""## Ćwiczenie 3.3: Multiple Dziedziczenie

Create classes demonstrating multiple inheritance:
1. `Flyable` - method `fly()`
2. `Swimmable` - method `swim()`
3. `Duck` - inherits both `Flyable` and `Swimmable`
"""

# Twój kod tutaj:
class Flyable:
    def fly(self):
        print("Flying in the sky!")


class Swimmable:
    def swim(self):
        print("Swimming in the water!")


class Duck(Flyable, Swimmable):
    def __init__(self, name):
        self.name = name

# Przetestuj swój kod:
duck = Duck("Donald")
duck.fly()
duck.swim()

"""### 💡 Rozwiązanie do Części 3"""

# Rozwiązanie 3.1: Vehicle and Car
class VehicleSolution:
    def __init__(self, brand, model, year):
        self.brand = brand
        self.model = model
        self.year = year

    def start_engine(self):
        print("Engine starting...")

class CarSolution(VehicleSolution):
    def __init__(self, brand, model, year, num_doors):
        super().__init__(brand, model, year)
        self.num_doors = num_doors

    def start_engine(self):
        print(f"{self.brand} {self.model}'s engine roaring to life!")

# Rozwiązanie 3.2: Multi-level inheritance
class AnimalSolution:
    def __init__(self, name, species):
        self.name = name
        self.species = species

class MammalSolution(AnimalSolution):
    def __init__(self, name, species, fur_color):
        super().__init__(name, species)
        self.fur_color = fur_color

class DogSolution(MammalSolution):
    def __init__(self, name, species, fur_color, breed):
        super().__init__(name, species, fur_color)
        self.breed = breed

    def bark(self):
        print(f"{self.name} says: Woof! Woof!")

# Rozwiązanie 3.3: Multiple inheritance
class FlyableSolution:
    def fly(self):
        print(f"{self.name} is flying!")

class SwimmableSolution:
    def swim(self):
        print(f"{self.name} is swimming!")

class DuckSolution(FlyableSolution, SwimmableSolution):
    def __init__(self, name):
        self.name = name

"""---
# Część 4: Polimorfizm

## What is Polimorfizm?

Polimorfizm means "many forms" - the ability of different objects to respond to the same method call in their own way.

## Types of Polimorfizm

1. **Nadpisywanie Metod**: Child class redefines parent's method
2. **Duck Typing**: "If it walks like a duck and quacks like a duck..."
3. **Operator Overloading**: Define custom behavior for operators

## Ćwiczenie 4.1: Nadpisywanie Metod

Create a base class `Shape` with method `area()`

Create child classes that override `area()`:
- `Circle` (radius)
- `Rectangle` (width, height)
- `Triangle` (base, height)
"""

# Twój kod tutaj:
import math

class Shape:
    pass  # Zastąp to swoją implementacją

class Circle(Shape):
    pass  # Zastąp to swoją implementacją

class Rectangle(Shape):
    pass  # Zastąp to swoją implementacją

class Triangle(Shape):
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
shapes = [
    Circle(5),
    Rectangle(4, 6),
    Triangle(3, 8)
]

for shape in shapes:
    print(f"{shape.__class__.__name__}: Area = {shape.area():.2f}")

"""## Ćwiczenie 4.2: Duck Typing

Create different classes that implement a `speak()` method:
- `Dog`, `Cat`, `Cow` (each with different `speak()` implementation)
- Create a function `make_sound(animal)` that calls `speak()`
"""

# Twój kod tutaj:
class Dog:
    pass  # Zastąp to swoją implementacją

class Cat:
    pass  # Zastąp to swoją implementacją

class Cow:
    pass  # Zastąp to swoją implementacją

def make_sound(animal):
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
animals = [Dog(), Cat(), Cow()]
for animal in animals:
    make_sound(animal)

"""### 💡 Rozwiązanie do Części 4"""

# Rozwiązanie 4.1: Shapes with polymorphism
import math

class ShapeSolution:
    def area(self):
        pass

class CircleSolution(ShapeSolution):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * self.radius ** 2

class RectangleSolution(ShapeSolution):
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def area(self):
        return self.width * self.height

class TriangleSolution(ShapeSolution):
    def __init__(self, base, height):
        self.base = base
        self.height = height

    def area(self):
        return 0.5 * self.base * self.height

# Rozwiązanie 4.2: Duck typing
class DogSolution:
    def speak(self):
        return "Woof! Woof!"

class CatSolution:
    def speak(self):
        return "Meow!"

class CowSolution:
    def speak(self):
        return "Moo!"

def make_sound_solution(animal):
    print(animal.speak())

"""---
# Część 5: Abstrakcja

## What is Abstrakcja?

Abstrakcja hides complex implementation details and shows only essential features.

## Abstrakcyjne Klasy Bazowe (ABC)

- Cannot be instantiated directly
- Force child classes to implement specific methods
- Use `@abstractmethod` decorator

## Ćwiczenie 5.1: Abstract Base Classes

Create an abstract class `Payment` z:
- Abstract method: `process_payment(amount)`
- Concrete method: `print_receipt(amount)`

Create concrete classes:
- `CreditCardPayment`
- `PayPalPayment`
- `CashPayment`
"""

# Twój kod tutaj:
from abc import ABC, abstractmethod

class Payment(ABC):
    pass  # Zastąp to swoją implementacją

class CreditCardPayment(Payment):
    pass  # Zastąp to swoją implementacją

class PayPalPayment(Payment):
    pass  # Zastąp to swoją implementacją

class CashPayment(Payment):
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
payments = [
    CreditCardPayment(),
    PayPalPayment(),
    CashPayment()
]

for payment in payments:
    payment.process_payment(100)
    payment.print_receipt(100)
    print()

"""### 💡 Rozwiązanie do Części 5"""

# Rozwiązanie 5.1: Abstract Payment classes
from abc import ABC, abstractmethod

class PaymentSolution(ABC):
    @abstractmethod
    def process_payment(self, amount):
        pass

    def print_receipt(self, amount):
        print(f"Receipt: ${amount} paid via {self.__class__.__name__}")

class CreditCardPaymentSolution(PaymentSolution):
    def process_payment(self, amount):
        print(f"Processing ${amount} via Credit Card...")

class PayPalPaymentSolution(PaymentSolution):
    def process_payment(self, amount):
        print(f"Processing ${amount} via PayPal...")

class CashPaymentSolution(PaymentSolution):
    def process_payment(self, amount):
        print(f"Received ${amount} in cash")

"""---
# Część 6: Metody Specjalne (Metody Magiczne)

## What are Special Methods?

Special methods (also called magic methods or dunder methods) are methods with double underscores that provide special functionality.

## Common Special Methods

- `__init__`: Constructor
- `__str__`: User-friendly string representation
- `__repr__`: Developer-friendly string representation
- `__len__`: Length
- `__getitem__`: Index access
- `__add__`, `__sub__`, etc.: Operator overloading

## Ćwiczenie 6.1: String Representation

Utwórz klasę `Product` z:
- Atrybuty: `name`, `price`, `quantity`
- Implement `__str__()` for user-friendly output
- Implement `__repr__()` for developer-friendly output
"""

# Twój kod tutaj:
class Product:
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
product = Product("Laptop", 999.99, 5)
print(str(product))   # User-friendly
print(repr(product))  # Developer-friendly
print(product)        # Uses __str__

"""## Ćwiczenie 6.2: Operator Overloading

Utwórz klasę `Vector2D` z:
- Atrybuty: `x`, `y`
- Implement `__add__()` for vector addition
- Implement `__sub__()` for vector subtraction
- Implement `__mul__()` for scalar multiplication
- Implement `__eq__()` for equality comparison
- Implement `__str__()` for display
"""

# Twój kod tutaj:
class Vector2D:
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
v1 = Vector2D(1, 2)
v2 = Vector2D(3, 4)

print(f"v1: {v1}")
print(f"v2: {v2}")
print(f"v1 + v2 = {v1 + v2}")
print(f"v2 - v1 = {v2 - v1}")
print(f"v1 * 3 = {v1 * 3}")
print(f"v1 == v2: {v1 == v2}")
print(f"v1 == Vector2D(1, 2): {v1 == Vector2D(1, 2)}")

"""## Ćwiczenie 6.3: Metody Kontenerowe

Utwórz klasę `Playlist` z:
- Store songs in a list
- Implement `__len__()` to return number of songs
- Implement `__getitem__()` to access songs by index
- Implement `__iter__()` to make it iterable
- Method `add_song(song)` to add a song
"""

# Twój kod tutaj:
class Playlist:
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
playlist = Playlist("My Favorites")
playlist.add_song("Song 1")
playlist.add_song("Song 2")
playlist.add_song("Song 3")

print(f"Playlist length: {len(playlist)}")
print(f"First song: {playlist[0]}")
print("\nAll songs:")
for song in playlist:
    print(f"  - {song}")

"""### 💡 Rozwiązanie do Części 6"""

# Rozwiązanie 6.1: Product with string methods
class ProductSolution:
    def __init__(self, name, price, quantity):
        self.name = name
        self.price = price
        self.quantity = quantity

    def __str__(self):
        return f"{self.name}: ${self.price} (Stock: {self.quantity})"

    def __repr__(self):
        return f"Product('{self.name}', {self.price}, {self.quantity})"

# Rozwiązanie 6.2: Vector2D with operators
class Vector2DSolution:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __add__(self, other):
        return Vector2DSolution(self.x + other.x, self.y + other.y)

    def __sub__(self, other):
        return Vector2DSolution(self.x - other.x, self.y - other.y)

    def __mul__(self, scalar):
        return Vector2DSolution(self.x * scalar, self.y * scalar)

    def __eq__(self, other):
        return self.x == other.x and self.y == other.y

    def __str__(self):
        return f"Vector2D({self.x}, {self.y})"

# Rozwiązanie 6.3: Playlist with container methods
class PlaylistSolution:
    def __init__(self, name):
        self.name = name
        self.songs = []

    def add_song(self, song):
        self.songs.append(song)

    def __len__(self):
        return len(self.songs)

    def __getitem__(self, index):
        return self.songs[index]

    def __iter__(self):
        return iter(self.songs)

"""---
# Część 7: Kompozycja

## What is Kompozycja?

Kompozycja is a "has-a" relationship where one class contains objects of other classes.

## Kompozycja vs Dziedziczenie

- **Dziedziczenie**: "is-a" relationship (Dog is-a Animal)
- **Kompozycja**: "has-a" relationship (Car has-a Engine)

**General rule**: Favor composition over inheritance for flexibility!

## Ćwiczenie 7.1: Relacja "Ma-"

Create a composition relationship:
1. `Engine` class - attributes: `horsepower`, `type`
2. `Car` class - has an `Engine` object
3. Demonstrate composition works differently from inheritance
"""

# Twój kod tutaj:
class Engine:
    pass  # Zastąp to swoją implementacją

class Car:
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
engine = Engine(200, "V6")
car = Car("Toyota", "Camry", engine)
car.display_info()

"""## Ćwiczenie 7.2: Complex Kompozycja

Create a university system using composition:
1. `Course` - attributes: `name`, `credits`
2. `Student` - attributes: `name`, `enrolled_courses` (list of Course objects)
3. `University` - attributes: `students` (list of Student objects)
   - Metody: `add_student()`, `enroll_student_in_course()`
"""

# Twój kod tutaj:
class Course:
    pass  # Zastąp to swoją implementacją

class Student:
    pass  # Zastąp to swoją implementacją

class University:
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
uni = University("Python University")

# Create courses
python_course = Course("Python Programming", 3)
oop_course = Course("Object-Oriented Programming", 4)

# Create and add student
student = Student("Alice", "S001")
uni.add_student(student)

# Enroll in courses
uni.enroll_student_in_course("S001", python_course)
uni.enroll_student_in_course("S001", oop_course)

# Display info
student.display_courses()

"""### 💡 Rozwiązanie do Części 7"""

# Rozwiązanie 7.1: Engine and Car composition
class EngineSolution:
    def __init__(self, horsepower, engine_type):
        self.horsepower = horsepower
        self.type = engine_type

    def info(self):
        return f"{self.horsepower}HP {self.type}"

class CarSolution:
    def __init__(self, brand, model, engine):
        self.brand = brand
        self.model = model
        self.engine = engine  # Composition

    def display_info(self):
        print(f"{self.brand} {self.model}")
        print(f"Engine: {self.engine.info()}")

# Rozwiązanie 7.2: University system
class CourseSolution:
    def __init__(self, name, credits):
        self.name = name
        self.credits = credits

class StudentSolution:
    def __init__(self, name, student_id):
        self.name = name
        self.student_id = student_id
        self.enrolled_courses = []

    def enroll(self, course):
        self.enrolled_courses.append(course)
        print(f"{self.name} enrolled in {course.name}")

    def display_courses(self):
        print(f"\n{self.name}'s courses:")
        for course in self.enrolled_courses:
            print(f"  - {course.name} ({course.credits} credits)")

class UniversitySolution:
    def __init__(self, name):
        self.name = name
        self.students = {}

    def add_student(self, student):
        self.students[student.student_id] = student
        print(f"Added {student.name} to {self.name}")

    def enroll_student_in_course(self, student_id, course):
        if student_id in self.students:
            self.students[student_id].enroll(course)
        else:
            print(f"Student {student_id} not found")

"""---
# Część 8: Metody Klasowe i Metody Statyczne

## Types of Methods

1. **Instance Methods**: Regular methods that work with instance data (use `self`)
2. **Class Methods**: Work with class data (use `@classmethod` and `cls`)
3. **Static Methods**: Don't access instance or class data (use `@staticmethod`)

## When to Use Each?

- **Instance method**: When you need to access/modify instance data
- **Class method**: Alternative constructors or when working with class attributes
- **Static method**: Utility functions related to the class but don't need class/instance data

## Ćwiczenie 8.1: Class Methods

Utwórz klasę `Date` z:
- Atrybuty instancji: `year`, `month`, `day`
- Instance method: `display()` to show the date
- Class method: `from_string(date_string)` to create Date from "DD-MM-YYYY"
- Class method: `today()` to create Date with current date
"""

# Twój kod tutaj:
from datetime import datetime

class Date:
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
# Using regular constructor
date1 = Date(2024, 12, 3)
date1.display()

# Using class method from_string
date2 = Date.from_string("25-12-2024")
date2.display()

# Using class method today
date3 = Date.today()
date3.display()

"""## Ćwiczenie 8.2: Static Methods

Utwórz klasę `MathOperations` with static methods:
- `is_prime(number)` - check if number is prime
- `factorial(number)` - calculate factorial
- `fibonacci(n)` - return nth Fibonacci number
"""

# Twój kod tutaj:
class MathOperations:
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
print(f"Is 17 prime? {MathOperations.is_prime(17)}")
print(f"Is 20 prime? {MathOperations.is_prime(20)}")
print(f"Factorial of 5: {MathOperations.factorial(5)}")
print(f"10th Fibonacci number: {MathOperations.fibonacci(10)}")

"""### 💡 Rozwiązanie do Części 8"""

# Rozwiązanie 8.1: Date with class methods
from datetime import datetime

class DateSolution:
    def __init__(self, year, month, day):
        self.year = year
        self.month = month
        self.day = day

    def display(self):
        print(f"{self.day:02d}-{self.month:02d}-{self.year}")

    @classmethod
    def from_string(cls, date_string):
        day, month, year = map(int, date_string.split('-'))
        return cls(year, month, day)

    @classmethod
    def today(cls):
        now = datetime.now()
        return cls(now.year, now.month, now.day)

# Rozwiązanie 8.2: Math operations with static methods
class MathOperationsSolution:
    @staticmethod
    def is_prime(number):
        if number < 2:
            return False
        for i in range(2, int(number ** 0.5) + 1):
            if number % i == 0:
                return False
        return True

    @staticmethod
    def factorial(number):
        if number <= 1:
            return 1
        return number * MathOperationsSolution.factorial(number - 1)

    @staticmethod
    def fibonacci(n):
        if n <= 1:
            return n
        a, b = 0, 1
        for _ in range(2, n + 1):
            a, b = b, a + b
        return b

"""---
# Część 9: Wzorce Projektowe

## What are Wzorce Projektowe?

Design patterns are reusable solutions to common problems in software design.

## Common Patterns

1. **Singleton**: Ensure only one instance exists
2. **Factory**: Create objects without specifying exact class
3. **Observer**: Objects observe and react to events
4. **Strategy**: Define family of algorithms

## Ćwiczenie 9.1: Wzorzec Singleton

Create a `Logger` class that:
- Only allows one instance to exist (Singleton)
- Has method `log(message)` to log messages
- Stores all logs in a list
"""

# Twój kod tutaj:
class Logger:
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
logger1 = Logger()
logger2 = Logger()

print(f"Same instance? {logger1 is logger2}")  # Should be True

logger1.log("First message")
logger2.log("Second message")

print("\nAll logs:")
for log in logger1.get_logs():
    print(f"  {log}")

"""## Ćwiczenie 9.2: Wzorzec Fabryki

Create a `ShapeFactory` that:
- Has a static method `create_shape(shape_type, *args)`
- Returns `Circle`, `Rectangle`, or `Triangle` based on `shape_type`
- Reuse your Shape classes from Exercise 4.1
"""

# Twój kod tutaj:
class ShapeFactory:
    pass  # Zastąp to swoją implementacją

# Przetestuj swój kod:
shapes = [
    ShapeFactory.create_shape("circle", 5),
    ShapeFactory.create_shape("rectangle", 4, 6),
    ShapeFactory.create_shape("triangle", 3, 8)
]

for shape in shapes:
    print(f"{shape.__class__.__name__}: Area = {shape.area():.2f}")

"""### 💡 Rozwiązanie do Części 9"""

# Rozwiązanie 9.1: Singleton Logger
class LoggerSolution:
    _instance = None
    _logs = []

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def log(self, message):
        self._logs.append(message)
        print(f"[LOG] {message}")

    def get_logs(self):
        return self._logs

# Rozwiązanie 9.2: Shape Factory
import math

class ShapeFactorySolution:
    @staticmethod
    def create_shape(shape_type, *args):
        if shape_type.lower() == "circle":
            return CircleSolution(*args)
        elif shape_type.lower() == "rectangle":
            return RectangleSolution(*args)
        elif shape_type.lower() == "triangle":
            return TriangleSolution(*args)
        else:
            raise ValueError(f"Unknown shape type: {shape_type}")

"""---
# Część 10: Projekt Końcowy - System Zarządzania Biblioteką

## Project Requirements

Create a complete library management system with the following classes:

### 1. Book Class
- Atrybuty: `title`, `author`, `isbn`, `is_available`
- Metody: `borrow()`, `return_book()`

### 2. Member Class
- Atrybuty: `name`, `member_id`, `borrowed_books` (list)
- Metody: `borrow_book(book)`, `return_book(book)`, `display_borrowed()`

### 3. Library Class
- Atrybuty: `books` (list), `members` (dictionary)
- Metody:
  - `add_book(book)`
  - `register_member(member)`
  - `lend_book(member_id, isbn)`
  - `receive_book(member_id, isbn)`
  - `display_available_books()`
  - `display_member_info(member_id)`

### Bonus Features (Optional)
- Add due dates for books
- Add fines for late returns
- Search functionality by title/author
- Book categories
"""

# Your implementation here:
class Book:
    pass  # Implement the Book class

class Member:
    pass  # Implement the Member class

class Library:
    pass  # Implement the Library class

# Test your library system:
# Create library
library = Library("City Library")

# Add books
book1 = Book("1984", "George Orwell", "ISBN001")
book2 = Book("The Hobbit", "J.R.R. Tolkien", "ISBN002")
book3 = Book("Python Crash Course", "Eric Matthes", "ISBN003")

library.add_book(book1)
library.add_book(book2)
library.add_book(book3)

# Register members
member1 = Member("Alice", "M001")
member2 = Member("Bob", "M002")

library.register_member(member1)
library.register_member(member2)

# Display available books
print("\n=== Available Books ===")
library.display_available_books()

# Borrow books
print("\n=== Borrowing Books ===")
library.lend_book("M001", "ISBN001")
library.lend_book("M001", "ISBN002")
library.lend_book("M002", "ISBN003")

# Display member info
print("\n=== Member Information ===")
library.display_member_info("M001")

# Display available books
print("\n=== Available Books After Borrowing ===")
library.display_available_books()

# Return a book
print("\n=== Returning Books ===")
library.receive_book("M001", "ISBN001")

# Display updated info
print("\n=== Updated Available Books ===")
library.display_available_books()

print("\n=== Updated Member Information ===")
library.display_member_info("M001")

"""### 💡 Pełne Rozwiązanie Projektu Końcowego"""

# Pełne Rozwiązanie Systemu Zarządzania Biblioteką

class BookSolution:
    def __init__(self, title, author, isbn):
        self.title = title
        self.author = author
        self.isbn = isbn
        self.is_available = True

    def borrow(self):
        if self.is_available:
            self.is_available = False
            return True
        return False

    def return_book(self):
        self.is_available = True

    def __str__(self):
        status = "Available" if self.is_available else "Borrowed"
        return f"'{self.title}' by {self.author} [{status}]"


class MemberSolution:
    def __init__(self, name, member_id):
        self.name = name
        self.member_id = member_id
        self.borrowed_books = []

    def borrow_book(self, book):
        if book.borrow():
            self.borrowed_books.append(book)
            print(f"{self.name} borrowed '{book.title}'")
            return True
        else:
            print(f"'{book.title}' is not available")
            return False

    def return_book(self, book):
        if book in self.borrowed_books:
            book.return_book()
            self.borrowed_books.remove(book)
            print(f"{self.name} returned '{book.title}'")
            return True
        else:
            print(f"{self.name} doesn't have '{book.title}'")
            return False

    def display_borrowed(self):
        if not self.borrowed_books:
            print(f"{self.name} has no borrowed books")
        else:
            print(f"{self.name}'s borrowed books:")
            for book in self.borrowed_books:
                print(f"  - {book.title} by {book.author}")


class LibrarySolution:
    def __init__(self, name):
        self.name = name
        self.books = {}
        self.members = {}

    def add_book(self, book):
        self.books[book.isbn] = book
        print(f"Added '{book.title}' to library")

    def register_member(self, member):
        self.members[member.member_id] = member
        print(f"Registered member: {member.name} ({member.member_id})")

    def lend_book(self, member_id, isbn):
        if member_id not in self.members:
            print(f"Member {member_id} not found")
            return False

        if isbn not in self.books:
            print(f"Book {isbn} not found")
            return False

        member = self.members[member_id]
        book = self.books[isbn]
        return member.borrow_book(book)

    def receive_book(self, member_id, isbn):
        if member_id not in self.members:
            print(f"Member {member_id} not found")
            return False

        if isbn not in self.books:
            print(f"Book {isbn} not found")
            return False

        member = self.members[member_id]
        book = self.books[isbn]
        return member.return_book(book)

    def display_available_books(self):
        available = [book for book in self.books.values() if book.is_available]

        if not available:
            print("No books available")
        else:
            print(f"Available books in {self.name}:")
            for book in available:
                print(f"  - {book}")

    def display_member_info(self, member_id):
        if member_id in self.members:
            member = self.members[member_id]
            print(f"\nMember: {member.name} ({member.member_id})")
            member.display_borrowed()
        else:
            print(f"Member {member_id} not found")

"""---
# 🎉 Gratulacje!

Ukończyłeś Warsztat Python OOP!

## Czego się Nauczyłeś

✅ Podstawy klas i obiektów
✅ Hermetyzacja with private attributes and properties
✅ Dziedziczenie (single, multi-level, multiple)
✅ Polimorfizm and duck typing
✅ Abstrakcja with ABC
✅ Metody specjalne (metody magiczne)
✅ Kompozycja over inheritance
✅ Metody klasowe i metody statyczne
✅ Wzorce projektowe (Singleton, Fabryka)
✅ Budowanie kompletnego projektu OOP

## Kolejne Kroki

1. **Praktyka**: Buduj własne projekty używając OOP
2. **Czytaj Kod**: Studiuj dobrze napisane biblioteki Pythona
3. **Ucz się Więcej Wzorców**: Poznawaj wzorce projektowe
4. **Adnotacje Typów**: Naucz się adnotacji typów w Pythonie
5. **Testowanie**: Naucz się pisać testy jednostkowe dla swoich klas

## Zasoby

- [Python Official Docs](https://docs.python.org/3/tutorial/classes.html)
- [Real Python - OOP](https://realpython.com/python3-object-oriented-programming/)
- [Wzorce Projektowe](https://refactoring.guru/design-patterns/python)

Programuj dalej! 🐍✨
"""